"""Export the FastAPI contract without starting external services."""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parents[1]))

from app.main import create_app


def main() -> None:
    schema = create_app().openapi()
    Path(__file__).parents[2].joinpath("openapi.yaml").write_text(
        "# Generated by `make openapi`; do not edit by hand.\n"
        + json.dumps(schema, ensure_ascii=False, indent=2)
        + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
